#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Regenerates docs/prompts/*.md from the current repository state.
 *
 * Nothing here is a prompt library. The slice intents live in tools/slices.json; every fact in the
 * generated prompts - file paths, line ranges, source excerpts, validation commands, the supported
 * PHP range, CI anchors - is derived by voku/agent-map and voku/agent-recall-compiler from the
 * repository as it exists right now. Re-run it after changing src/ and the prompts follow.
 *
 * Requirements (deliberately not Composer dependencies of this library):
 *
 *   composer global require voku/agent-map voku/agent-recall-compiler
 *
 * Usage:
 *
 *   php tools/generate-slice-prompts.php [--agent-map=PATH] [--agent-recall=PATH]
 */

$repositoryRoot = dirname(__DIR__);
chdir($repositoryRoot);

$options = getopt('', ['agent-map::', 'agent-recall::']);
$agentMap = is_string($options['agent-map'] ?? null) ? $options['agent-map'] : locateBinary('agent-map');
$agentRecall = is_string($options['agent-recall'] ?? null) ? $options['agent-recall'] : locateBinary('agent-recall-compiler');

$mapIndex = '.agent-map/php-symbols.json';
$learningRoot = '.agent-loop/learning';
$recallOutputRoot = '.agent-recall';
$promptDir = 'docs/prompts';

run([PHP_BINARY, $agentMap, 'build', '--root=.', '--paths=src,tests', '--out=' . $mapIndex]);

$slices = decodeSlices('tools/slices.json');
$generated = [];

foreach ($slices as $slice) {
    $outputDir = $recallOutputRoot . '/' . $slice['id'];

    $command = [
        PHP_BINARY,
        $agentRecall,
        'compile',
        '--root', $learningRoot,
        '--task', $slice['id'],
        '--description', $slice['description'],
        '--map-index', $mapIndex,
        '--map-root', $repositoryRoot,
        '--output-dir', $outputDir,
        '--compilation-id', 'compilation.' . $slice['id'] . '.generated',
        '--operating-prompt', json_encode($slice['operating_prompt'], JSON_THROW_ON_ERROR),
        '--operating-prompt-manifest', operatingPromptManifest($agentRecall),
    ];

    foreach ($slice['targets'] as $target) {
        array_push($command, '--target', $target);
    }

    foreach ($slice['files'] as $file) {
        array_push($command, '--file', $file);
    }

    run($command);

    $promptFile = $promptDir . '/' . strtolower($slice['id']) . '.md';
    file_put_contents($promptFile, normalizePaths(renderPrompt($slice, $outputDir), [
        dirname($agentRecall, 2) => 'vendor/voku/agent-recall-compiler',
        dirname($agentMap, 2) => 'vendor/voku/agent-map',
        $repositoryRoot => '.',
    ]));
    $generated[] = $promptFile;
}

file_put_contents($promptDir . '/README.md', renderIndex($slices));

echo "Generated:\n  " . implode("\n  ", [...$generated, $promptDir . '/README.md']) . "\n";

/**
 * Rewrites the absolute paths of this machine's checkouts into stable, checked-in-friendly ones.
 *
 * Only tool install locations and the repository root are rewritten; every repository fact in the
 * briefing is already recorded relative to the repository root, so provenance is unaffected.
 *
 * @param array<string, string> $replacements
 */
function normalizePaths(string $content, array $replacements): string
{
    foreach ($replacements as $absolute => $stable) {
        $content = str_replace($absolute . '/', $stable . '/', $content);
    }

    return $content;
}

/**
 * @param array{id: string, title: string, description: string, operating_prompt: array{id: string, arguments: array<string, scalar>}} $slice
 */
function renderPrompt(array $slice, string $outputDir): string
{
    $header = <<<MD
    <!-- GENERATED by tools/generate-slice-prompts.php - do not edit by hand. -->
    # {$slice['title']}

    Copy everything below the line into a fresh coding agent. It is self-contained: the repository
    facts, source ranges, and validation commands were derived from this checkout at generation time,
    not written by hand. Regenerate with `php tools/generate-slice-prompts.php` after changing `src/`.

    Slice id: `{$slice['id']}` &middot; L2 recipe: `{$slice['operating_prompt']['id']}`

    ---

    MD;

    return $header
        . "\n"
        . readGenerated($outputDir . '/system.md')
        . "\n\n"
        . readGenerated($outputDir . '/validation-plan.md')
        . "\n";
}

/**
 * @param list<array{id: string, title: string, description: string, operating_prompt: array{id: string, arguments: array<string, scalar>}}> $slices
 */
function renderIndex(array $slices): string
{
    $rows = '';
    foreach ($slices as $slice) {
        $file = strtolower($slice['id']) . '.md';
        $rows .= "| [`{$slice['id']}`]({$file}) | {$slice['title']} | `{$slice['operating_prompt']['id']}` |\n";
    }

    return <<<MD
    <!-- GENERATED by tools/generate-slice-prompts.php - do not edit by hand. -->
    # Pre-1.0 slice prompts

    One copy&paste-ready prompt per independently mergeable slice. Each one carries the repository
    evidence it needs - exact files, line ranges, source excerpts, project-native validation commands,
    and the declared PHP range - resolved deterministically from this checkout rather than recalled
    from memory.

    | Slice | Intent | L2 recipe |
    | ----- | ------ | --------- |
    {$rows}
    Regenerate them all:

    ```bash
    php tools/generate-slice-prompts.php
    ```

    MD;
}

/**
 * @return list<array{id: string, title: string, description: string, targets: list<string>, files: list<string>, operating_prompt: array{id: string, arguments: array<string, scalar>}}>
 */
function decodeSlices(string $path): array
{
    $decoded = json_decode(readGenerated($path), true, 512, JSON_THROW_ON_ERROR);
    if (!is_array($decoded) || !isset($decoded['slices']) || !is_array($decoded['slices'])) {
        fail($path . ' must contain a "slices" array.');
    }

    /** @var list<array{id: string, title: string, description: string, targets: list<string>, files: list<string>, operating_prompt: array{id: string, arguments: array<string, scalar>}}> $slices */
    $slices = array_values($decoded['slices']);

    return $slices;
}

function operatingPromptManifest(string $agentRecall): string
{
    $manifest = dirname($agentRecall, 2) . '/resources/skills/agent-recall-consumer/operating-prompts.json';
    if (!is_file($manifest)) {
        fail('Cannot find the bundled operating-prompt manifest next to ' . $agentRecall . '.');
    }

    return $manifest;
}

function locateBinary(string $name): string
{
    foreach (['vendor/bin/' . $name, getenv('HOME') . '/.composer/vendor/bin/' . $name, getenv('HOME') . '/.config/composer/vendor/bin/' . $name] as $candidate) {
        if (is_file($candidate)) {
            return $candidate;
        }
    }

    fail('Cannot find "' . $name . '". Install it or pass --' . $name . '=PATH.');
}

function readGenerated(string $path): string
{
    $content = file_get_contents($path);
    if ($content === false) {
        fail('Cannot read ' . $path . '.');
    }

    return $content;
}

/**
 * @param list<string> $command
 */
function run(array $command): void
{
    $process = proc_open($command, [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
    if (!is_resource($process)) {
        fail('Cannot start: ' . implode(' ', $command));
    }

    $stdout = (string) stream_get_contents($pipes[1]);
    $stderr = (string) stream_get_contents($pipes[2]);
    fclose($pipes[1]);
    fclose($pipes[2]);

    if (proc_close($process) !== 0) {
        fail(implode(' ', $command) . "\n" . $stdout . $stderr);
    }

    echo $stdout;
}

function fail(string $message): never
{
    fwrite(STDERR, $message . "\n");

    exit(1);
}
